from __future__ import annotations

from pathlib import Path


WRAPPER_TEMPLATE = r'''# Generated by load-gen. Do not edit by hand.
import importlib.util
import json
import math
import os
import time
from pathlib import Path

import gevent
from gevent.lock import Semaphore
from locust import LoadTestShape
from locust.clients import HttpSession
from locust.contrib.fasthttp import FastHttpSession
from locust.user import User


APP_LOCUSTFILE = Path({app_locustfile!r})
spec = importlib.util.spec_from_file_location("loadgen_app_locustfile", APP_LOCUSTFILE)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)  # type: ignore[union-attr]

_loadgen_lock = Semaphore()
_loadgen_next_request_at = time.monotonic()
_loadgen_started_at = time.monotonic()


def _loadgen_no_wait(_self):
    return 0.0


for _loadgen_name, _loadgen_value in vars(module).items():
    if _loadgen_name.startswith("_"):
        continue
    if isinstance(_loadgen_value, type) and issubclass(_loadgen_value, User) and _loadgen_value.abstract is False:
        _loadgen_value.wait_time = _loadgen_no_wait
        globals()[_loadgen_name] = _loadgen_value
del _loadgen_name, _loadgen_value


def _parse_duration(value):
    if isinstance(value, (int, float)):
        return float(value)
    text = str(value).strip()
    total = 0.0
    number = ""
    units = {{"h": 3600.0, "m": 60.0, "s": 1.0}}
    for ch in text:
        if ch.isdigit() or ch == ".":
            number += ch
        elif ch in units and number:
            total += float(number) * units[ch]
            number = ""
        else:
            raise ValueError(f"unsupported duration: {{value!r}}")
    if number:
        raise ValueError(f"unsupported duration: {{value!r}}")
    return total


def _duration(pattern):
    kind = pattern.get("type")
    if kind in ("constant", "sinusoidal", "exponential"):
        return _parse_duration(pattern["duration"])
    if kind == "mixed":
        return sum(_duration(part) for part in pattern.get("parts", []))
    raise ValueError(f"unsupported pattern type: {{kind!r}}")


def _rps_at(pattern, t_s):
    kind = pattern.get("type")
    if kind == "constant":
        return max(0.0, float(pattern["rps"]))
    if kind == "sinusoidal":
        baseline = float(pattern["baseline_rps"])
        amplitude = float(pattern["amplitude_rps"])
        period_s = _parse_duration(pattern["period"])
        phase_s = _parse_duration(pattern.get("phase", 0))
        return max(0.0, baseline + amplitude * math.sin((2.0 * math.pi * (t_s + phase_s)) / period_s))
    if kind == "exponential":
        start = float(pattern["start_rps"])
        end = float(pattern["end_rps"])
        duration_s = max(_duration(pattern), 1.0)
        curve = float(pattern.get("curve", 3.0))
        progress = min(max(t_s / duration_s, 0.0), 1.0)
        if abs(curve) < 1e-9:
            value = start + (end - start) * progress
        else:
            shaped = (math.exp(curve * progress) - 1.0) / (math.exp(curve) - 1.0)
            value = start + (end - start) * shaped
        return max(0.0, value)
    if kind == "mixed":
        cursor = 0.0
        parts = pattern.get("parts", [])
        for part in parts:
            part_duration = _duration(part)
            if t_s < cursor + part_duration:
                return _rps_at(part, t_s - cursor)
            cursor += part_duration
        return _rps_at(parts[-1], _duration(parts[-1])) if parts else 0.0
    raise ValueError(f"unsupported pattern type: {{kind!r}}")


_loadgen_pattern = json.loads(os.environ["LOADGEN_PATTERN_JSON"])


def _loadgen_wait_for_request_slot():
    global _loadgen_next_request_at
    while True:
        run_time = time.monotonic() - _loadgen_started_at
        target_rps = _rps_at(_loadgen_pattern, run_time)
        if target_rps <= 0:
            with _loadgen_lock:
                _loadgen_next_request_at = time.monotonic()
            gevent.sleep(0.1)
            continue

        now = time.monotonic()
        with _loadgen_lock:
            max_schedule_ahead_s = max(1.0, 2.0 / target_rps)
            if _loadgen_next_request_at > now + max_schedule_ahead_s:
                _loadgen_next_request_at = now
            slot_at = max(now, _loadgen_next_request_at)
            _loadgen_next_request_at = slot_at + (1.0 / target_rps)
        delay = slot_at - now
        if delay > 0:
            gevent.sleep(delay)
        return


_loadgen_original_http_request = HttpSession.request
_loadgen_original_fast_http_request = FastHttpSession.request


def _loadgen_http_request(self, *args, **kwargs):
    _loadgen_wait_for_request_slot()
    return _loadgen_original_http_request(self, *args, **kwargs)


def _loadgen_fast_http_request(self, *args, **kwargs):
    _loadgen_wait_for_request_slot()
    return _loadgen_original_fast_http_request(self, *args, **kwargs)


HttpSession.request = _loadgen_http_request
FastHttpSession.request = _loadgen_fast_http_request


class LoadGenShape(LoadTestShape):
    pattern = _loadgen_pattern
    spawn_rate = float(os.environ.get("LOADGEN_SPAWN_RATE", "10.0"))
    duration_s = _duration(pattern)

    def tick(self):
        run_time = self.get_run_time()
        if run_time > self.duration_s:
            return None
        target_rps = _rps_at(self.pattern, run_time)
        users = max(1, int(math.ceil(target_rps))) if target_rps > 0 else 0
        return (users, self.spawn_rate)
'''


def write_wrapper(app_locustfile: Path, output_path: Path) -> Path:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        WRAPPER_TEMPLATE.format(app_locustfile=str(app_locustfile.resolve())),
        encoding="utf-8",
    )
    return output_path
